package com.company.classes.model;

public enum TableIdentifiers {
    ADDRESSES, CUSTOMER_ADDRESSES, COMPANIES, INDIVIDUALS, ACCOUNTS, POST_PAID_CONTRACTS, PRE_PAID_CONTRACTS,
    POST_PAID_TARIFFS, PRE_PAID_TARIFFS
}
